name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'  # or 3.9, 3.10, etc.
    
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Pylint
      run: |
        PYTHONPATH=${{ github.workspace }} 
        pylint sorted_column_scraper/column_sorter.py 
        pylint tests/*.py $PYLINT_TEST_OPTIONS
      env:
        PYLINT_TEST_OPTIONS: "--disable=missing-function-docstring,protected-access,too-many-public-methods,redefined-outer-name"
